basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path('', views.basket_summary, name = 'basket_summary'),
    path('add/', views.basket_add, name = 'basket_add'),
    path('delete/', views.basket_delete, name = 'basket_delete'),
    path('update/',views.basket_update, name = 'basket_update')
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('book/<slug:slug>', views.product_detail, name='product_detail'),
    path('type/<slug:category_slug>', views.category_list, name='category_list'),
]

basket/models.py
from django.db import models

# Create your models here.

store/models.py
from account.models import UserAcc as User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active = True)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creater', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default = 'images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
    def __str__(self):
        return self.title

basket/views.py
from django.http import JsonResponse
from django.shortcuts import render, get_object_or_404
from .basket import Basket
from store.models import Product

def basket_summary(request):
    basket = Basket(request)
    return render(request, 'store/basket/summary.html', {'basket':basket})

def basket_add(request):
    basket = Basket(request)

    #if request received from ajax is POST
    if request.POST.get('action') == 'post' :
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        product = get_object_or_404(Product, id=product_id)
        basket.add(product=product, qty=product_qty)
        basket_qty = basket.__len__()
        response = JsonResponse({'qty' : basket_qty}) #return updated quantity to frontend
        return response

def basket_update(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        product_qty = int(request.POST.get('productqty'))
        basket.update(product=product_id, qty=product_qty)
        return JsonResponse({'Success':'True'})

def basket_delete(request):
    basket = Basket(request)

    if request.POST.get('action') == 'post':
        product_id = int(request.POST.get('productid'))
        basket.remove(product=product_id)
        response = JsonResponse({'Success':'True'})
        return response

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


#test123


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'store/products/single.html', {'product':product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.objects.filter(category = category)
    return render(request, 'store/products/category.html', {'category': category, 'products':products})

templates/store/basket/summary.html
{% extends "../base.html" %}
{% load static %}


{% block title %}
Basket Summary
{% endblock title %}

{% block content %}

<div class="container">
  <div class="col-12">
    <h1 class="h2">Your Basket</h1>
  </div>
  <hr />
</div>

<div class="container">
  <div class="row g-3">
    {% if basket|length == 0 %}
    <div class="col-12">Your basket is empty <a href="{% url 'store:product_all' %}">Shop</a></div>
    {% else %}
    <div class="col-12 bg-light p-3 d-flex justify-content-between">
      <div class="d-flex d-flex-inline">
        <div class="pe-3">Order</div>
        <div class="dropdown">
          <a class="text-reset text-decoration-none dropdown-toggle" href="#" role="link" id="dropdownLink"
            data-bs-toggle="dropdown" aria-expanded="false">
            Shipping options
          </a>
          <ul class="dropdown-menu" aria-labelledby="dropdownLink">
            <li class="item small">Next day delivery</li>
            <li class="item small">Premimum delivery</li>
          </ul>
        </div>
      </div>
      <div class="text-end">
        <div class="">Sub Total: <span class="fw-bold">Rs.</span>
          <div id="subtotal" class="d-inline-flex fw-bold">{{basket.get_sub_total}}</div>
        </div>
        <div id="">Shipping <span class="small">(Next day delivery)</span>: <span class="fw-bold"></span></div>
        <div class="pt-2">Total to pay: <span class="fw-bold h5">Rs.</span><span id="total"
            class="fw-bold h5">{{basket.get_sub_total}}</span></div>
      </div>
    </div>
    <div class="col-md-5 col-lg-4 order-md-last p-0 order-3">
      <div class="d-grid gap-2 ">
        <a role="button" href="" class="btn btn-success fw-bold" type="button">Checkout</a>
        <button class="btn btn-light" type="button">Save for later</button>
      </div>
    </div>
    <div class="col-md-7 col-lg-8 p-0">
      {% for item in basket %}
      {% with product=item.product %}
      <div class="card mb-3 border-0 product-item" data-index="{{product.id}}">
        <div class="row g-0">
          <div class="col-md-2 d-none d-md-block">
            <img class="img-fluid mx-auto d-block" alt="Responsive image" src="{{ product.image.url }}" />
          </div>
          <div class="col-md-10 ps-md-3">
            <div class="card-body p-1">
              <a class="text-decoration-none text-reset" href="{{item.product.get_absolute_url}}">
                <p class="card-text pb-3">{{product.title}}</p>
              </a>
              <label for="select">Qty</label>
              <select id="select{{product.id}}" style="width:50px;height:31px;">
                <option value="" selected disabled hidden>{{item.qty}}</option>
                <option value="">1</option>
                <option value="">2</option>
                <option value="">3</option>
                <option value="">4</option>
              </select>
              <a type="button" id="update-button" data-index="{{product.id}}"
                class="update-button text-decoration-none small ps-3">Update</a>
              <a type="button" id="delete-button" data-index="{{product.id}}"
                class="delete-button text-decoration-none small">Delete</a>
            </div>
          </div>
        </div>
      </div>
      {% endwith %}
      {% endfor %}
    </div>
    {% endif %}
  </div>
</div>

<script>
    $(document).on('click', '.delete-button', function (e) {
        e.preventDefault();
        var product_id = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_delete" %}',
            data: {
                productid: $(this).data('index'),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'post'
            },
            success: function (json) {
                location.reload(true);
            },
            error: function (xhr, errmsg, err) {}
        });
    })

    $(document).on('click', '.update-button', function (e) {
        e.preventDefault();
        var product_id = $(this).data('index');
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_update" %}',
            data: {
                productid: $(this).data('index'),
                productqty: $('#select'+ product_id +' option:selected').text(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'post'
            },
            success: function (json) {
                location.reload(true);
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>
{% endblock content %}