basket/urls.py
from django.urls import path

from . import views

app_name = "basket"

urlpatterns = [
    path('', views.basket_summary, name = 'basket_summary'),
    path('add/', views.basket_add, name = 'basket_add'),
    path('delete/', views.basket_delete, name = 'basket_delete'),
    path('update/',views.basket_update, name = 'basket_update')
]

core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('store.urls', namespace='store')),
    path('basket/', include('basket.urls', namespace='basket')),
    path('account/', include('account.urls', namespace='account')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

store/urls.py
from django.urls import path

from . import views

app_name = 'store'

urlpatterns = [
    path('', views.product_all, name='product_all'),
    path('book/<slug:slug>', views.product_detail, name='product_detail'),
    path('type/<slug:category_slug>', views.category_list, name='category_list'),
]

store/models.py
from account.models import UserAcc as User
from django.db import models
from django.urls import reverse


class Category(models.Model):
    name = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, unique=True)

    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse('store:category_list', args=[self.slug])
    
    def __str__(self):
        return self.name


class ProductManager(models.Manager):
    def get_queryset(self):
        return super(ProductManager, self).get_queryset().filter(is_active = True)

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='product', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, related_name='product_creater', on_delete = models.CASCADE)
    title = models.CharField(max_length=255)
    author = models.CharField(max_length=255, default='admin')
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='images/', default = 'images/default.png')
    slug = models.SlugField(max_length=255)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    in_stock = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    objects = models.Manager()
    products = ProductManager()

    class Meta:
        ordering = ('-created',)

    def get_absolute_url(self):
        return reverse('store:product_detail', args=[self.slug])
    
    def __str__(self):
        return self.title

store/views.py
from django.shortcuts import get_object_or_404, render

from .models import Category, Product


#test123


def product_all(request):
    products = Product.products.all()
    return render(request, 'store/home.html', {'products': products})

def product_detail(request, slug):
    product = get_object_or_404(Product, slug = slug, in_stock = True)
    return render(request, 'store/products/single.html', {'product':product})

def category_list(request, category_slug):
    category = get_object_or_404(Category, slug = category_slug)
    products = Product.objects.filter(category = category)
    return render(request, 'store/products/category.html', {'category': category, 'products':products})

templates/store/products/category.html
{% extends "../base.html" %}
{% load static %}

{% block title %} {{ category.name|title }} {% endblock %}

{% block content %}
<main>

<div class="album py-5 bg-light">
    <div class="container">
    <div class="pb-3 h5">{{ category.name|title }} Books</div>
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for product in products %}
            <div class="col" style = "width:200px">
                <div class="card shadow-sm">
                    <img class="img-fluid" width="200px" alt = "Responsive image" src = "{{ product.image.url }}">
                        <div class="card-body">
                            <p class="card-text">
                            <a class = "text-dark text-decoration-none" href = "{{ product.get_absolute_url }}">{{ product.title }}</a>
                            </p>
                            <div class="d-flex justify-content-between align-items-center">
                            <small class="text-muted">9 mins</small>
                            </div>
                        </div>
                </div>
            </div>
        {% endfor %}
    </div>
    </div>
    </div>


</main>
{% endblock %}

templates/store/products/single.html
{% extends "../base.html" %}
{% load static %}

{% block title %} {{ product.name }} {% endblock %}

{% block content %}

<div class="container">
    <main class="pt-5">
        <div class="row g-3">
            <div class="col-md-5 col-lg-5 order-md-first bg-light">
                <img class="img-fluid mx-auto d-block" width="200px" alt="Responsive image" src="{{ product.image.url }}">
            </div>
            <div class="col-md-7 col-lg-7 ps-md-3 ps-lg-5">
                <h1 class="mb-0 h4">{{ product.title }}</h1>
                <p><span class="lead">{{ product.author }}</span> (Author)</p>
                <p>{{ product.description|slice:":355" }}...</p>
                <div class="border">
                    <div class="col border-bottom">
                        <div class="row p-3">
                            <div class="col-6">Hardback</div>
                            <div class="col-6 text-end"><span class="h4 fw-bold">Rs. {{ product.price }}</span></div>
                        </div>
                    </div>
                    <div class="col">
                        <div class="row p-3">
                            <div class="col-6">
                                <label for="select">Qty</label>
                                <select id="select">
                                    <option value="1">1</option>
                                    <option value="2">2</option>
                                    <option value="3">3</option>
                                    <option value="4">4</option>
                                </select>

                            </div>
                            <div class="col-6 text-end">
                            <button type="button"  id="add-button" value="{{ product.id }}" class="btn btn-success fw500">Add to basket</button></div>
                        </div>
                    </div>
                </div>
            </div>
            <div id="shop"><a href="{% url 'store:product_all' %}">Back to Shop</a></div>
        </div>
    </main>

</div>

<script>
    $(document).on('click', '#add-button', function(e) {
        e.preventDefault();
        $.ajax({
            type: 'POST',
            url: '{% url "basket:basket_add" %}',
            data: {
                productqty: $('#select option:selected').text(),
                productid: $('#add-button').val(),
                csrfmiddlewaretoken: "{{ csrf_token }}",
                action: 'post'
            },
            success: function (json) {
                /*document.getElementById("basket-qty").innerHTML = json.qty
                document.getElementById("success-text").innerHTML = "Success !"*/
                location.reload(true);
            },
            error: function (xhr, errmsg, err) {}
        });
    })
</script>

{% endblock %}